[theme]
base = "light"
primaryColor = "#0066CC"
# backgroundColor = "#ffffff"  <-- Let Streamlit default to white
# secondaryBackgroundColor = "#f0f2f6"
# textColor = "#262730"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
